version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: lesson05_postgres
    environment:
      POSTGRES_DB: taskapi
      POSTGRES_USER: taskuser
      POSTGRES_PASSWORD: taskpass
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U taskuser -d taskapi"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - taskapi_network

  # Application (database version)
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lesson05_app
    environment:
      - DATABASE_URL=postgres://taskuser:taskpass@postgres:5432/taskapi?sslmode=disable
      - PORT=8080
      - APP_ENV=development
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - taskapi_network

volumes:
  postgres_data:

networks:
  taskapi_network:
    driver: bridge